"""add transit key versioning

Revision ID: c9200e6b99a4
Revises: 265d97c458fe
Create Date: 2026-07-31 09:49:20.604267

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c9200e6b99a4"
down_revision: str | Sequence[str] | None = "265d97c458fe"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transit_key_versions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("transit_key_id", sa.String(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("key_nonce", sa.LargeBinary(), nullable=True),
        sa.Column("wrapped_key_ciphertext", sa.LargeBinary(), nullable=True),
        sa.Column("public_key", sa.LargeBinary(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.CheckConstraint("version >= 1", name="ck_transit_key_versions_version_positive"),
        sa.ForeignKeyConstraint(["transit_key_id"], ["transit_keys.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "transit_key_id", "version", name="uq_transit_key_versions_key_id_version"
        ),
    )
    op.create_index(
        op.f("ix_transit_key_versions_transit_key_id"),
        "transit_key_versions",
        ["transit_key_id"],
        unique=False,
    )
    op.add_column(
        "transit_keys",
        sa.Column("current_version", sa.Integer(), server_default="1", nullable=False),
    )
    op.drop_column("transit_keys", "public_key")
    op.drop_column("transit_keys", "wrapped_key_ciphertext")
    op.drop_column("transit_keys", "key_nonce")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("transit_keys", sa.Column("key_nonce", sa.BLOB(), nullable=True))
    op.add_column("transit_keys", sa.Column("wrapped_key_ciphertext", sa.BLOB(), nullable=True))
    op.add_column("transit_keys", sa.Column("public_key", sa.BLOB(), nullable=True))
    op.drop_column("transit_keys", "current_version")
    op.drop_index(op.f("ix_transit_key_versions_transit_key_id"), table_name="transit_key_versions")
    op.drop_table("transit_key_versions")
    # ### end Alembic commands ###
